resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604

variables:
  ContainerRegistry: beyondpl.azurecr.io
  AzureSubscriptionEndpoint: k8s-workshop
steps:

- task: Docker@1
  displayName: 'Build an image - API'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscriptionEndpoint)
    azureContainerRegistry: $(ContainerRegistry)
    dockerFile: app/api/Dockerfile
    imageName: '$(Build.Repository.Name)/rating-api:$(Build.BuildNumber)'
    buildArguments: |
     VCS_REF=$(Build.SourceVersion)
     BUILD_DATE=$(SYSTEM.PIPELINESTARTTIME)
     IMAGE_TAG_REF=$(Build.BuildNumber)

- task: Docker@1
  displayName: 'Push an image - API'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscriptionEndpoint)
    azureContainerRegistry: $(ContainerRegistry)
    command: 'Push an image'
    imageName: '$(Build.Repository.Name)/rating-api:$(Build.BuildNumber)'

- task: Docker@1
  displayName: 'Build an image - WEB'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscriptionEndpoint)
    azureContainerRegistry: $(ContainerRegistry)
    dockerFile: app/web/Dockerfile
    imageName: '$(Build.Repository.Name)/rating-web:$(Build.BuildNumber)'
    buildArguments: |
     VCS_REF=$(Build.SourceVersion)
     BUILD_DATE=$(SYSTEM.PIPELINESTARTTIME)
     IMAGE_TAG_REF=$(Build.BuildNumber)

- task: Docker@1
  displayName: 'Push an image - WEB'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscriptionEndpoint)
    azureContainerRegistry: $(ContainerRegistry)
    command: 'Push an image'
    imageName: '$(Build.Repository.Name)/rating-web:$(Build.BuildNumber)'

- task: Docker@1
  displayName: 'Build an image - DB'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscriptionEndpoint)
    azureContainerRegistry: $(ContainerRegistry)
    dockerFile: app/db/Dockerfile
    imageName: '$(Build.Repository.Name)/rating-db:$(Build.BuildNumber)'
    buildArguments: |
     VCS_REF=$(Build.SourceVersion)
     BUILD_DATE=$(SYSTEM.PIPELINESTARTTIME)
     IMAGE_TAG_REF=$(Build.BuildNumber)

- task: Docker@1
  displayName: 'Push an image - DB'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscriptionEndpoint)
    azureContainerRegistry: $(ContainerRegistry)
    command: 'Push an image'
    imageName: '$(Build.Repository.Name)/rating-db:$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'app/heroes-k8s-deployment.yaml' 
    artifactName: 'heroes-k8s-deployment'