resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:

- script: printenv

- task: Docker@1
  displayName: 'Build an image - API'
  inputs:
    azureSubscriptionEndpoint: 'k8s-workshop'
    azureContainerRegistry: beyondpl.azurecr.io
    dockerFile: app/api/Dockerfile
    imageName: '$(Build.Repository.Name)/api:$(Build.BuildNumber)'

- task: Docker@1
  displayName: 'Push an image - API'
  inputs:
    azureSubscriptionEndpoint: 'k8s-workshop'
    azureContainerRegistry: beyondpl.azurecr.io
    command: 'Push an image'
    imageName: '$(Build.Repository.Name)/api:$(Build.BuildNumber)'

- task: Docker@1
  displayName: 'Build an image - WEB'
  inputs:
    azureSubscriptionEndpoint: 'k8s-workshop'
    azureContainerRegistry: beyondpl.azurecr.io
    dockerFile: app/web/Dockerfile
    imageName: '$(Build.Repository.Name)/web:$(Build.BuildNumber)'
    buildArguments: |
     VCS_REF=$(Build.SourceVersion)
     BUILD_DATE=
     IMAGE_TAG_REF=$(Build.BuildNumber)

- task: Docker@1
  displayName: 'Push an image - WEB'
  inputs:
    azureSubscriptionEndpoint: 'k8s-workshop'
    azureContainerRegistry: beyondpl.azurecr.io
    command: 'Push an image'
    imageName: '$(Build.Repository.Name)/web:$(Build.BuildNumber)'

- task: Docker@1
  displayName: 'Build an image - DB'
  inputs:
    azureSubscriptionEndpoint: 'k8s-workshop'
    azureContainerRegistry: beyondpl.azurecr.io
    dockerFile: app/db/Dockerfile
    imageName: '$(Build.Repository.Name)/db:$(Build.BuildNumber)'

- task: Docker@1
  displayName: 'Push an image - DB'
  inputs:
    azureSubscriptionEndpoint: 'k8s-workshop'
    azureContainerRegistry: beyondpl.azurecr.io
    command: 'Push an image'
    imageName: '$(Build.Repository.Name)/db:$(Build.BuildNumber)'
