apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: heroes-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  heroes-api-deploy
  labels:
    name:  heroes-api
    ReleaseName: #{Release.ReleaseName}#
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: heroes-api
      ReleaseName: #{Release.ReleaseName}#
  template:
    metadata:
      labels:
        name:  heroes-api
        ReleaseName: #{Release.ReleaseName}#
    spec:
      containers:
      - image: #{ContainerRegistry}#/#{Build.Repository.Name}#/rating-api:#{Build.BuildNumber}#
        name:  heroes-api-cntnr
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: heroes-secret
              key: MONGODB_URI
        - name: APPINSIGHTS_INSTRUMENTATION_KEY
          valueFrom:
            secretKeyRef:
              name: heroes-secret
              key: APPINSIGHTS_INSTRUMENTATION_KEY
        ports:
        - containerPort:  3000
          name:  heroes-api
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: heroes-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  heroes-web-deploy
  labels:
    name:  heroes-web
    ReleaseName: #{Release.ReleaseName}#
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: heroes-web
      ReleaseName: #{Release.ReleaseName}#
  template:
    metadata:
      labels:
        name:  heroes-web
        ReleaseName: #{Release.ReleaseName}#
    spec:
      containers:
      - image: #{ContainerRegistry}#/#{Build.Repository.Name}#/rating-web:#{Build.BuildNumber}#
        name:  heroes-web-cntnr
        env:
        - name:  API
          value:  http://api:3000/
        - name: APPINSIGHTS_INSTRUMENTATION_KEY
          valueFrom:
            secretKeyRef:
              name: heroes-secret
              key: APPINSIGHTS_INSTRUMENTATION_KEY
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort:  8080
          name:  heroes-web
      restartPolicy: Always
